server {
    listen 80;
    listen [::]:80;
    server_name __DOMAIN__;

    location /.well-known/acme-challenge/ {
        root /www/wwwroot/_acme-challenge;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name __DOMAIN__;

    ssl_certificate /root/websites/nginx-config/ssl/jijiangeshui.com.cer;
    ssl_certificate_key /root/websites/nginx-config/ssl/jijiangeshui.com.key;
    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:10m;
    ssl_session_tickets off;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;

    access_log /var/log/nginx/__DOMAIN__.access.log;
    error_log /var/log/nginx/__DOMAIN__.error.log;
    client_max_body_size 20m;

    location / {
        proxy_pass http://127.0.0.1:__APP_PORT__;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_cache_bypass $http_upgrade;
    }

    location /_next/static/ {
        alias __DEPLOY_PATH__/current/.next/static/;
        access_log off;
        expires 365d;
        add_header Cache-Control "public, max-age=31536000, immutable";
    }

    location /assets/ {
        alias __DEPLOY_PATH__/current/public/assets/;
        access_log off;
        expires 365d;
        add_header Cache-Control "public, max-age=31536000, immutable";
    }

    # /github 路径需要和v2ray服务器端，客户端保持一致
    location /github {
        proxy_redirect off;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        set $is_v2ray 0;
        if ($http_upgrade = "websocket") {
          set $is_v2ray 1;
        }

        if ($is_v2ray = 1) {
          # 此IP地址和端口需要和v2ray服务器保持一致，
          proxy_pass http://127.0.0.1:26100;
        }
    }

      # 代理到贴吧云签到
      location /tieba {
        proxy_redirect off;

        # 此IP地址和端口需要和v2ray服务器保持一致，
        proxy_pass http://127.0.0.1:9800/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;

        sub_filter 'source/css/' '/tieba/source/css/';
        sub_filter 'source/js/' '/tieba/source/js/';
        sub_filter 'index.php?mod=' '/tieba?mod=';
        sub_filter_once off;
      }
}
